apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: vallegrande
data:
  URL_END: "https://api.groq.com/openai/v1/chat/completions"
  SPRING_PROFILES_ACTIVE: "prod"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: vallegrande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: elsermanuel/elsermanueldocker
        ports:
        - containerPort: 8085
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: URL_MONGO
          valueFrom:
            secretKeyRef:
              name: microservice-secret
              key: URL_MONGO
        - name: URL_CLOUD
          valueFrom:
            secretKeyRef:
              name: microservice-secret
              key: URL_CLOUD
        - name: URL_END
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: URL_END
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservice-config
              key: SPRING_PROFILES_ACTIVE
---
apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
  namespace: vallegrande
type: Opaque
data:
  URL_CLOUD: QmVhcmVyIGdzazZGRkJhMEFYTGtkYzZOWlJRMnV4V0dkeWIzRlk5djdadjVpaVdsbXBYc2l5MU1DOFg3dXU=
  URL_MONGO: bW9uZ29kYitzcnY6Ly9lbHNlcmxhemFybzpNcm9VeFpNOENiWExNUEtrQGNsdXN0ZXIwLmJydnl2Lm1vbmdvZGIubmV0L01vbmdvQXRsYUNvbXBvbnM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: vallegrande
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
