name: SonarCloud
on:
  push:
    branches:
      - Micro_Actions
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verify Java version
        run: java -version

      - name: Verify Maven version
        run: mvn -version

      - name: Debug environment variables
        run: |
          echo "Database URL: ${{ secrets.DATABASE_URL }}"
          echo "Database Username: ${{ secrets.DATABASE_USERNAME }}"
          echo "Sonar Token: ${{ secrets.SONAR_TOKEN }}"

      - name: Build and analyze with verbose logging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          mvn -X verify \
            -Dsonar.projectKey=KasandraChumpitazChipana_ApiCognitivo \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dspring.datasource.url=${{ secrets.DATABASE_URL }} \
            -Dspring.datasource.username=${{ secrets.DATABASE_USERNAME }} \
            -Dspring.datasource.password=${{ secrets.DATABASE_PASSWORD }} \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
