name: SonarCloud
on:
  push:
    branches:
      - Micro_Actions
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'  # Alternative distributions like 'adopt' or 'temurin' are also available

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Database URL environment variable
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}  # Database username environment variable
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}  # Database password environment variable
        run: |
          mvn -X verify \
            -Dsonar.projectKey=KasandraChumpitazChipana_ApiCognitivo \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dspring.datasource.url=${{ secrets.DATABASE_URL }} \
            -Dspring.datasource.username=${{ secrets.DATABASE_USERNAME }} \
            -Dspring.datasource.password=${{ secrets.DATABASE_PASSWORD }} \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
